### ISSUE TITLE
cannot run convert_imagesToKlg

### ISSUE THREAD

**Issue by sumitsarkar1** [martinruenz/dataset-tools#1]
I have installed the library and able to run convert_klg successfully. However the application convert_imagesToKlg doesnt work. I run ./convert_ImagesToKlg --depthdir /.../.../ --rgbdir /.../.../ --out /.../.../output.klg . The klg file is build but when run with ElasticFusion nothing appears to be seen on the gui of elasticfusion. Even the .ply file generated by EF is empty. Pl help

**Comment by martinruenz** [comment]
Which depth-scale do the images have? (Depth images are png files I assume?)
My guess is that you didn't use the `-s` parameter correctly and depth values are cut-off by EF.

**Comment by sumitsarkar1** [comment]
depth images are png
-s is for skipping initial frames....but why would i skip initial frames....if you are talking about -d option of EF then its 6 in my case i.e. -d 6 and most of my environment lies inside 6 mtr

**Comment by martinruenz** [comment]
We are talking about this [program](https://github.com/martinruenz/dataset-tools/blob/master/convert_imagesToKlg/main.cpp), right?
Please double-check the input parameters.

**Comment by sumitsarkar1** [comment]
thnx... -s 0.001 did the job
